In [1]:
import json
import requests
from config import api_key
import datetime
import pandas as pd

In [2]:
from pprint import pprint

# Main API

### EIA Data Sets > Petroleum > Prices > Weekly Retail Gasoline and Diesel Prices > by Area > California

In [3]:
#https://www.eia.gov/opendata/qb.php?category=240839

# Establishes my URL string
url_cali = 'http://api.eia.gov/category/?api_key=YOUR_API_KEY_HERE&category_id=240839'

# Inserts my API key
url_new_cali = url_cali.replace('YOUR_API_KEY_HERE', api_key)

In [4]:
# Converts to json
api_response = requests.get(url_new_cali)
api_json_cali = api_response.json()

In [5]:
pprint(api_json_cali)

{'category': {'category_id': '240839',
              'childcategories': [],
              'childseries': [{'f': 'A',
                               'name': 'California No 2 Diesel Ultra Low '
                                       'Sulfur (0-15 ppm) Retail Prices, '
                                       'Annual',
                               'series_id': 'PET.EMD_EPD2DXL0_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '06-JAN-20 05.29.11 PM'},
                              {'f': 'M',
                               'name': 'California No 2 Diesel Ultra Low '
                                       'Sulfur (0-15 ppm) Retail Prices, '
                                       'Monthly',
                               'series_id': 'PET.EMD_EPD2DXL0_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'W',
                               'name': 'California No 2 Diesel Ultra Low '
                                       'Sulfur (0-15 ppm) Retail Prices, '
                                       'Weekly',
                               'series_id': 'PET.EMD_EPD2DXL0_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California No 2 Diesel Retail Prices, '
                                       'Annual',
                               'series_id': 'PET.EMD_EPD2D_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '06-JAN-20 05.29.11 PM'},
                              {'f': 'M',
                               'name': 'California No 2 Diesel Retail Prices, '
                                       'Monthly',
                               'series_id': 'PET.EMD_EPD2D_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'W',
                               'name': 'California No 2 Diesel Retail Prices, '
                                       'Weekly',
                               'series_id': 'PET.EMD_EPD2D_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California All Grades Reformulated '
                                       'Retail Gasoline Prices, Annual',
                               'series_id': 'PET.EMM_EPM0R_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '16-MAY-16 04.56.05 PM'},
                              {'f': 'M',
                               'name': 'California All Grades Reformulated '
                                       'Retail Gasoline Prices, Monthly',
                               'series_id': 'PET.EMM_EPM0R_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '16-MAY-16 04.56.05 PM'},
                              {'f': 'W',
                               'name': 'California All Grades Reformulated '
                                       'Retail Gasoline Prices, Weekly',
                               'series_id': 'PET.EMM_EPM0R_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California All Grades All Formulations '
                                       'Retail Gasoline Prices, Annual',
                               'series_id': 'PET.EMM_EPM0_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '06-JAN-20 05.29.11 PM'},
                              {'f': 'M',
                               'name': 'California All Grades All Formulations '
                                       'Retail Gasoline Prices, Monthly',
                               'series_id': 'PET.EMM_EPM0_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'W',
                               'name': 'California All Grades All Formulations '
                                       'Retail Gasoline Prices, Weekly',
                               'series_id': 'PET.EMM_EPM0_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California Midgrade Reformulated '
                                       'Retail Gasoline Prices, Annual',
                               'series_id': 'PET.EMM_EPMMR_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '16-MAY-16 04.56.05 PM'},
                              {'f': 'M',
                               'name': 'California Midgrade Reformulated '
                                       'Retail Gasoline Prices, Monthly',
                               'series_id': 'PET.EMM_EPMMR_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '16-MAY-16 04.56.05 PM'},
                              {'f': 'W',
                               'name': 'California Midgrade Reformulated '
                                       'Retail Gasoline Prices, Weekly',
                               'series_id': 'PET.EMM_EPMMR_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California Midgrade All Formulations '
                                       'Retail Gasoline Prices, Annual',
                               'series_id': 'PET.EMM_EPMM_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '06-JAN-20 05.29.11 PM'},
                              {'f': 'M',
                               'name': 'California Midgrade All Formulations '
                                       'Retail Gasoline Prices, Monthly',
                               'series_id': 'PET.EMM_EPMM_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'W',
                               'name': 'California Midgrade All Formulations '
                                       'Retail Gasoline Prices, Weekly',
                               'series_id': 'PET.EMM_EPMM_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California Premium Reformulated Retail '
                                       'Gasoline Prices, Annual',
                               'series_id': 'PET.EMM_EPMPR_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '16-MAY-16 04.56.05 PM'},
                              {'f': 'M',
                               'name': 'California Premium Reformulated Retail '
                                       'Gasoline Prices, Monthly',
                               'series_id': 'PET.EMM_EPMPR_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '16-MAY-16 04.56.05 PM'},
                              {'f': 'W',
                               'name': 'California Premium Reformulated Retail '
                                       'Gasoline Prices, Weekly',
                               'series_id': 'PET.EMM_EPMPR_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California Premium All Formulations '
                                       'Retail Gasoline Prices, Annual',
                               'series_id': 'PET.EMM_EPMP_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '06-JAN-20 05.29.11 PM'},
                              {'f': 'M',
                               'name': 'California Premium All Formulations '
                                       'Retail Gasoline Prices, Monthly',
                               'series_id': 'PET.EMM_EPMP_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'W',
                               'name': 'California Premium All Formulations '
                                       'Retail Gasoline Prices, Weekly',
                               'series_id': 'PET.EMM_EPMP_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California Regular Reformulated Retail '
                                       'Gasoline Prices, Annual',
                               'series_id': 'PET.EMM_EPMRR_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '16-MAY-16 04.56.05 PM'},
                              {'f': 'M',
                               'name': 'California Regular Reformulated Retail '
                                       'Gasoline Prices, Monthly',
                               'series_id': 'PET.EMM_EPMRR_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '16-MAY-16 04.56.05 PM'},
                              {'f': 'W',
                               'name': 'California Regular Reformulated Retail '
                                       'Gasoline Prices, Weekly',
                               'series_id': 'PET.EMM_EPMRR_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'A',
                               'name': 'California Regular All Formulations '
                                       'Retail Gasoline Prices, Annual',
                               'series_id': 'PET.EMM_EPMR_PTE_SCA_DPG.A',
                               'units': 'Dollars per Gallon',
                               'updated': '06-JAN-20 05.29.11 PM'},
                              {'f': 'M',
                               'name': 'California Regular All Formulations '
                                       'Retail Gasoline Prices, Monthly',
                               'series_id': 'PET.EMM_EPMR_PTE_SCA_DPG.M',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'},
                              {'f': 'W',
                               'name': 'California Regular All Formulations '
                                       'Retail Gasoline Prices, Weekly',
                               'series_id': 'PET.EMM_EPMR_PTE_SCA_DPG.W',
                               'units': 'Dollars per Gallon',
                               'updated': '30-MAR-20 07.07.48 PM'}],
              'name': 'California',
              'notes': '',
              'parent_category_id': '240691'},
 'request': {'category_id': 240839, 'command': 'category'}}

# Annual API

### EIA Data Sets > Petroleum > Prices > Weekly Retail Gasoline and Diesel Prices > by Area > California > Annual

In [6]:
# https://www.eia.gov/opendata/qb.php?category=240839&sdid=PET.EMM_EPM0_PTE_SCA_DPG.A

# Establishes my URL string
url_annual = 'http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=PET.EMM_EPM0_PTE_SCA_DPG.A'

# Inserts my API key
url_new_annual = url_annual.replace('YOUR_API_KEY_HERE', api_key)

In [91]:
# Converts to json
api_response = requests.get(url_new_annual)
api_json_annual = api_response.json()

In [92]:
# pprint(api_json_annual)

In [93]:
# Navigates to key: series
api_json_series_a = api_json_annual['series']

# changes list back to dictionary
api_json_series_a = api_json_series_a[0]

# Navigates to key: data
api_json_data_a = api_json_series_a['data']

In [94]:
# api_json_data_a

In [95]:
# iterates through list prep for data frame
yearly_list = [['Year', 'Price']]
for i in api_json_data_a:
    yearly_list.append([i[0], i[1]])

# Creates DataFrame
yearly_df = pd.DataFrame(yearly_list[1:],columns=yearly_list[0])

# Drops Nan rows
yearly_df = yearly_df.dropna()

In [88]:
yearly_df

    Year  Price
0   2019  3.677
1   2018  3.551
2   2017  3.080
3   2016  2.782
4   2015  3.221
5   2014  3.794
6   2013  3.933
7   2012  4.081
8   2011  3.863
9   2010  3.138
10  2009  2.725
11  2008  3.561
12  2007  3.124
13  2006  2.855
14  2005  2.517
15  2004  2.166
16  2003  1.878
17  2002  1.561
18  2001  1.677

In [103]:
file_path = '..\Output\Annual_Prices.csv'

yearly_df.to_csv(file_path, index=False)

# Monthly API

### EIA Data Sets > Petroleum > Prices > Weekly Retail Gasoline and Diesel Prices > by Area > California > Monthly

In [96]:
# https://www.eia.gov/opendata/qb.php?category=240839&sdid=PET.EMM_EPM0_PTE_SCA_DPG.A

# Establishes my URL string
url_month = 'http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=PET.EMM_EPM0_PTE_SCA_DPG.M'

# Inserts my API key
url_new_month = url_month.replace('YOUR_API_KEY_HERE', api_key)

In [97]:
# Converts to json
api_response = requests.get(url_new_month)
api_json_month = api_response.json()

In [98]:
# pprint(api_json_month)

In [14]:
# Navigates to key: series
api_json_series_m = api_json_month['series']

# changes list back to dictionary
api_json_series_m = api_json_series_m[0]

# Navigates to key: data
api_json_data_m = api_json_series_m['data']

In [79]:
# api_json_data_m

In [70]:
# Preps a list for iteration
dates_list_m = [['Year', 'Month', 'Price']]

# Iterates through list and parses the date into separate year, month rows
for i in api_json_data_m:
    long_date = i[0]
    parsed_date = datetime.datetime.strptime(long_date, '%Y%m')
    year = parsed_date.date().year
    month = parsed_date.date().month
    dates_list_m.append([year, month, i[1]])

# Creates dataframe from list
monthly_df = pd.DataFrame(dates_list_m[1:],columns=dates_list_m[0])

In [74]:
monthly_df

     Year  Month  Price
0    2020      3  3.262
1    2020      2  3.447
2    2020      1  3.489
3    2019     12  3.610
4    2019     11  3.944
..    ...    ...    ...
234  2000      9  1.869
235  2000      8  1.720
236  2000      7  1.754
237  2000      6  1.669
238  2000      5    NaN

[239 rows x 3 columns]

In [104]:
file_path = '..\Output\Monthly_Prices.csv'

monthly_df.to_csv(file_path, index=False)

# Weekly API

### EIA Data Sets > Petroleum > Prices > Weekly Retail Gasoline and Diesel Prices > by Area > California > Weekly

In [19]:
# https://www.eia.gov/opendata/qb.php?category=240839&sdid=PET.EMM_EPM0_PTE_SCA_DPG.A

# Establishes my URL string
url_week = 'http://api.eia.gov/series/?api_key=YOUR_API_KEY_HERE&series_id=PET.EMM_EPM0_PTE_SCA_DPG.W'

# Inserts my API key
url_new_week = url_week.replace('YOUR_API_KEY_HERE', api_key)

In [20]:
# Converts to json
api_response = requests.get(url_new_week)
api_json_week = api_response.json()

In [78]:
# pprint(api_json_week)

In [22]:
api_json_series_w = api_json_week['series']
api_json_series_w = api_json_series_w[0]
api_json_data_w = api_json_series_w['data']

In [77]:
# api_json_data_w

In [100]:
# Preps a list for iteration
dates_list_w = [['Year', 'Month', 'Day', 'Price']]

# Iterates through list and parses the date into separate year, month rows
for i in api_json_data_w:
        long_date = i[0]
        parsed_date = datetime.datetime.strptime(long_date, '%Y%m%d')
        year = parsed_date.date().year
        month = parsed_date.date().month
        day = parsed_date.date().day
        dates_list_w.append([year, month, day, i[1]])
        
# Creates dataframe from list
weekly_df = pd.DataFrame(dates_list_w[1:],columns=dates_list_w[0])

In [101]:
weekly_df

      Year  Month  Day  Price
0     2020      3   30  3.031
1     2020      3   23  3.142
2     2020      3   16  3.298
3     2020      3    9  3.403
4     2020      3    2  3.435
...    ...    ...  ...    ...
1032  2000      6   19  1.664
1033  2000      6   12  1.662
1034  2000      6    5  1.661
1035  2000      5   29  1.673
1036  2000      5   22  1.679

[1037 rows x 4 columns]

In [105]:
file_path = '..\Output\weekly_Prices.csv'

weekly_df.to_csv(file_path, index=False)